MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [256, 512, 256, 256, 128, 64]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[40,30], [20,15], [10,8], [5,4], [3,2], [1,1]]
INPUT:
    #IMAGE_SIZE: (512,384)
    IMAGE_SIZE: (320,240)
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 50000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-2
    WEIGHT_DECAY: 0.005
OUTPUT_DIR: 'outputs/basic'
DATASET_DIR: "datasets"